version: '3'
services:
  docker-mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: journal
      MYSQL_USER: aj
      MYSQL_PASSWORD: aj
    restart: always
    volumes:
    - /data/mysql
  docker-mongodb:
    image: mongo:latest
    container_name: "docker-mongodb"
    restart: always
    ports:
    - 27017:27017
  journal-app:
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
    - /data/journal-app
    depends_on:
      - docker-mysql
      - docker-mongodb
    links:
      - docker-mongodb
      - docker-mysql
